ARDUINO_DIR  = /usr/share/arduino
# ARDMK_DIR     = /usr
AVR_TOOLS_DIR = /usr

ARDUINO_LIBS = Servo common EEPROM
BOARD_TAG = mega2560
ARDUINO_PORT = /dev/ttyACM0
# BOARD_TAG = fio
# ARDUINO_PORT = /dev/ttyUSB0


USER_LIB_PATH = ../..

include /usr/share/arduino/Arduino.mk
