/* ( pin,role,        group name,    human readable name) */
X(   22, SINGLE_MOTOR,  HAUTEUR, "Hauteur du mannequin")
X(   23, LEFT_MOTOR,  TOUR_POITRINE, "Tour de poitrine")
X(   24, RIGHT_MOTOR,  TOUR_POITRINE, "Tour de poitrine")
X(   25, FRONT_MOTOR,  TOUR_POITRINE, "Tour de poitrine")
X(   26, BACK_MOTOR,  TOUR_POITRINE, "Tour de poitrine")
X(   27, LEFT_MOTOR,  TOUR_TAILLE, "Tour de taille")
X(   28, RIGHT_MOTOR,  TOUR_TAILLE, "Tour de taille")
X(   29, FRONT_MOTOR,  TOUR_TAILLE, "Tour de taille")
X(   30, BACK_MOTOR,  TOUR_TAILLE, "Tour de taille")
X(   31, LEFT_MOTOR,  TOUR_HANCHE, "Tour de hanche")
X(   32, RIGHT_MOTOR,  TOUR_HANCHE, "Tour de hanche")
X(   33, FRONT_MOTOR,  TOUR_HANCHE, "Tour de hanche")
X(   34, BACK_MOTOR,  TOUR_HANCHE, "Tour de hanche")
